In [4]:
import pandas as pd
import math
from tqdm import tqdm

#log the LEIE dataset
crime_col_names =['LASTNAME','FIRSTNAME','MIDNAME','BUSNAME','GENERAL','SPECIALTY','UPIN','NPI','DOB','ADDRESS','CITY','STATE','ZIP','EXCLTYPE','EXCLDATE','REINDATE','WAIVERDATE','WVRSTATE']
crime_data = pd.read_csv('LEIE\LEIE.csv', header = None, names = crime_col_names)
crime_data = pd.DataFrame(crime_data).loc[1:].reset_index(drop=True)

crime_data

,LASTNAME,FIRSTNAME,MIDNAME,BUSNAME,GENERAL,SPECIALTY,UPIN,NPI,DOB,ADDRESS,CITY,STATE,ZIP,EXCLTYPE,EXCLDATE,REINDATE,WAIVERDATE,WVRSTATE
0,NaN,NaN,,"#1 MARKETING SERVICE, INC",OTHER BUSINESS,SOBER HOME,NaN,0000000000,NaN,239 BRIGHTON BEACH AVENUE,BROOKLYN,NY,11235,1128a1,20200319,00000000,00000000,NaN
1,NaN,NaN,,101 FIRST CARE PHARMACY INC,OTHER BUSINESS,PHARMACY,NaN,1972902351,NaN,"C/O 609 W 191ST STREET, APT D",NEW YORK,NY,10040,1128b8,20220320,00000000,00000000,NaN
2,NaN,NaN,,14 LAWRENCE AVE PHARMACY,PHARMACY,NaN,NaN,0000000000,NaN,14 LAWRENCE AVENUE,SMITHTOWN,NY,11787,1128a1,19880830,00000000,00000000,NaN
3,NaN,NaN,,143 MEDICAL EQUIPMENT CO,DME COMPANY,DME - OXYGEN,NaN,0000000000,NaN,701 NW 36 AVENUE,MIAMI,FL,33125,1128b7,19970620,00000000,00000000,NaN
4,NaN,NaN,,184TH STREET PHARMACY CORP,OTHER BUSINESS,PHARMACY,NaN,1922348218,NaN,69 E 184TH ST,BRONX,NY,10468,1128a1,20180419,00000000,00000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9945,BOREL,MONIQUE,RENEE,NaN,IND- LIC HC SERV PRO,NURSE/NURSES AIDE,NaN,0000000000,19790820,14151 HIGHWAY 395,ROANOKE,LA,70581,1128b4,20150720,00000000,00000000,NaN
9946,BORELA,LINCOLN,ARTHUR,NaN,HOSPITAL,NURSE/NURSES AIDE,NaN,0000000000,19640410,231 S CEDAR ST,BELLE PLAINE,MN,56011,1128a2,20040819,00000000,00000000,NaN
9947,BORELLI,ANTHONY,,NaN,STATE/LOCAL/TRIBAL A,HEALTH CARE AIDE,NaN,0000000000,19750322,2692 JANELLE WAY,EUGENE,OR,97404,1128b5,20110420,00000000,00000000,NaN
9948,BOREN,KATHLEEN,S,NaN,NURSING PROFESSION,NURSE/NURSES AIDE,NaN,0000000000,19590106,26 DANKIN STREET,CONCORD,NH,03301,1128b4,19940606,00000000,00000000,NaN
9949,BOREN,MICHAEL,CHARLES,NaN,IND- LIC HC SERV PRO,DENTIST,NaN,1407945744,19691014,3559 BALTIMORE AVENUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#Extract data on crimes committed in 2017 and later
crime_data_2017 = []
nan = str('nan')
zero = '0000000000'

for row in tqdm(crime_data.itertuples()):
    if str(getattr(row, 'EXCLDATE')) != nan:
        if int(str(getattr(row, 'EXCLDATE'))[0:4]) >= 2017:
            if getattr(row, 'NPI') != zero:
                crime_data_2017.append(row)
                
crime_data_2017 = pd.DataFrame(crime_data_2017)

9950it [00:00, 399064.09it/s]

In [8]:
crime_data_2017

,Index,LASTNAME,FIRSTNAME,MIDNAME,BUSNAME,GENERAL,SPECIALTY,UPIN,NPI,DOB,ADDRESS,CITY,STATE,ZIP,EXCLTYPE,EXCLDATE,REINDATE,WAIVERDATE,WVRSTATE
0,1,NaN,NaN,,101 FIRST CARE PHARMACY INC,OTHER BUSINESS,PHARMACY,NaN,1972902351,NaN,"C/O 609 W 191ST STREET, APT D",NEW YORK,NY,10040,1128b8,20220320,00000000,00000000,NaN
1,4,NaN,NaN,,184TH STREET PHARMACY CORP,OTHER BUSINESS,PHARMACY,NaN,1922348218,NaN,69 E 184TH ST,BRONX,NY,10468,1128a1,20180419,00000000,00000000,NaN
2,24,NaN,NaN,,"A & Y MEDICAL SUPPLY, INC",DME COMPANY,DME - GENERAL,NaN,1942476080,NaN,"6310 108TH STREET, APT 6J",FOREST HILLS,NY,11375,1128b8,20170518,00000000,00000000,NaN
3,31,NaN,NaN,,"A FAIR DEAL PHARMACY, INC",OTHER BUSINESS,PHARMACY,NaN,1891731758,NaN,"C/O P O BOX 329014, #69709-05",BROOKLYN,NY,11232,1128b8,20170518,00000000,00000000,NaN
4,60,NaN,NaN,,"ACACIA MENTAL HEALTH CLINIC, L",OTHER BUSINESS,MENTAL/BEHAVIORAL HE,NaN,1851631543,NaN,5228 W FOND DU LAC AVENUE,MILWAUKEE,WI,53216,1128b7,20190326,00000000,00000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461,9709,BOLDRIDGE-GROSS,JANE,ANN,NaN,IND- LIC HC SERV PRO,SOCIAL WORKER,NaN,1699954388,19650326,"9457 S UNIVERSITY BLVD, APT 17",HIGHLANDS RANCH,CO,80126,1128a3,20170920,00000000,00000000,NaN
462,9720,BOLGER,PAUL,MATTHEW,NaN,"PHYSICIAN (MD, DO)",EMERGENCY MEDICINE,NaN,1376516609,19710923,"P O BOX 1000, #18202-030",MARION,IL,62959,1128a3,20190820,00000000,00000000,NaN
463,9743,BOLLING,GEORGE,RICHARD JR,NaN,IND- LIC HC SERV PRO,PHARMACIST,NaN,1932373735,19610707,"MAXWELL AFB, #33500-001",MONTGOMERY,AL,36112,1128a4,20180419,00000000,00000000,NaN
464,9938,BORDEN,WENDY,LYNN,NaN,EMPLOYEE - PRIVATE S,COUNSELING CENTER,NaN,1700216231,19730410,140 NORTH SEMINOLE LANE,LAKE ALFRED,FL,33850,1128a1,20220220,00000000,00000000,NaN
465,9942,BORDERS-BLACKWELL,ANNIE,,NaN,"PHYSICIAN (MD, DO)",GYN/OBS,NaN,1891750923,19570404,"820 WILLOW STREET, #36903-034",MONTGOMERY,AL,36112,1128a4,20171120,00000000,00000000,NaN

In [13]:
#Save the generated crime 2017 data
crime_data_2017.to_csv('crime_data/crime_Data_2017.csv',index = False)

In [9]:
#Extract data on crimes committed in 2018 and later
crime_data_2018 = []
nan = str('nan')
zero = '0000000000'

for row in tqdm(crime_data.itertuples()):
    if str(getattr(row, 'EXCLDATE')) != nan:
        if int(str(getattr(row, 'EXCLDATE'))[0:4]) >= 2018:
            if getattr(row, 'NPI') != zero:
                crime_data_2018.append(row)
                
crime_data_2018 = pd.DataFrame(crime_data_2018)

9950it [00:00, 369514.39it/s]

In [10]:
crime_data_2018

,Index,LASTNAME,FIRSTNAME,MIDNAME,BUSNAME,GENERAL,SPECIALTY,UPIN,NPI,DOB,ADDRESS,CITY,STATE,ZIP,EXCLTYPE,EXCLDATE,REINDATE,WAIVERDATE,WVRSTATE
0,1,NaN,NaN,,101 FIRST CARE PHARMACY INC,OTHER BUSINESS,PHARMACY,NaN,1972902351,NaN,"C/O 609 W 191ST STREET, APT D",NEW YORK,NY,10040,1128b8,20220320,00000000,00000000,NaN
1,4,NaN,NaN,,184TH STREET PHARMACY CORP,OTHER BUSINESS,PHARMACY,NaN,1922348218,NaN,69 E 184TH ST,BRONX,NY,10468,1128a1,20180419,00000000,00000000,NaN
2,60,NaN,NaN,,"ACACIA MENTAL HEALTH CLINIC, L",OTHER BUSINESS,MENTAL/BEHAVIORAL HE,NaN,1851631543,NaN,5228 W FOND DU LAC AVENUE,MILWAUKEE,WI,53216,1128b7,20190326,00000000,00000000,NaN
3,62,NaN,NaN,,"ACCESS 2 INTEGRATION, INC",OTHER BUSINESS,CONSULTING FIRM,NaN,1073916631,NaN,16095 PROSPERITY DR,NOBLESVILLE,IN,46060,1128b7,20210816,00000000,00000000,NaN
4,115,NaN,NaN,,"AFFORDABLE PHARMACY, INC",OTHER BUSINESS,PHARMACY,NaN,1801231436,NaN,"8030 FM 1765, STE A104",TEXAS CITY,TX,77591,1128a1,20211029,00000000,00000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371,9675,BOHLMAN,PETER,ANDREW JR,NaN,IND- LIC HC SERV PRO,PHYSICIAN ASSISTANT,NaN,1013064914,19670507,328 PINE STREET,SOUTH HEMPSTEAD,NY,11550,1128b4,20220119,00000000,00000000,NaN
372,9684,BOINPALLY,ASHOK,,NaN,"PHYSICIAN (MD, DO)",PEDIATRICS,NaN,1255421384,19520801,26868 HOLLY HILL DRIVE,FARMINGTON HILLS,MI,48334,1128a1,20200720,00000000,00000000,NaN
373,9720,BOLGER,PAUL,MATTHEW,NaN,"PHYSICIAN (MD, DO)",EMERGENCY MEDICINE,NaN,1376516609,19710923,"P O BOX 1000, #18202-030",MARION,IL,62959,1128a3,20190820,00000000,00000000,NaN
374,9743,BOLLING,GEORGE,RICHARD JR,NaN,IND- LIC HC SERV PRO,PHARMACIST,NaN,1932373735,19610707,"MAXWELL AFB, #33500-001",MONTGOMERY,AL,36112,1128a4,20180419,00000000,00000000,NaN
375,9938,BORDEN,WENDY,LYNN,NaN,EMPLOYEE - PRIVATE S,COUNSELING CENTER,NaN,1700216231,19730410,140 NORTH SEMINOLE LANE,LAKE ALFRED,FL,33850,1128a1,20220220,00000000,00000000,NaN

In [14]:
#Save the generated crime 2018 data
crime_data_2018.to_csv('crime_data/crime_Data_2018.csv',index = False)

In [11]:
#Extract data on crimes committed in 2019 and later
crime_data_2019 = []
nan = str('nan')
zero = '0000000000'

for row in tqdm(crime_data.itertuples()):
    if str(getattr(row, 'EXCLDATE')) != nan:
        if int(str(getattr(row, 'EXCLDATE'))[0:4]) >= 2019:
            if getattr(row, 'NPI') != zero:
                crime_data_2019.append(row)
                
crime_data_2019 = pd.DataFrame(crime_data_2019)

9950it [00:00, 113434.13it/s]

In [12]:
crime_data_2019

,Index,LASTNAME,FIRSTNAME,MIDNAME,BUSNAME,GENERAL,SPECIALTY,UPIN,NPI,DOB,ADDRESS,CITY,STATE,ZIP,EXCLTYPE,EXCLDATE,REINDATE,WAIVERDATE,WVRSTATE
0,1,NaN,NaN,,101 FIRST CARE PHARMACY INC,OTHER BUSINESS,PHARMACY,NaN,1972902351,NaN,"C/O 609 W 191ST STREET, APT D",NEW YORK,NY,10040,1128b8,20220320,00000000,00000000,NaN
1,60,NaN,NaN,,"ACACIA MENTAL HEALTH CLINIC, L",OTHER BUSINESS,MENTAL/BEHAVIORAL HE,NaN,1851631543,NaN,5228 W FOND DU LAC AVENUE,MILWAUKEE,WI,53216,1128b7,20190326,00000000,00000000,NaN
2,62,NaN,NaN,,"ACCESS 2 INTEGRATION, INC",OTHER BUSINESS,CONSULTING FIRM,NaN,1073916631,NaN,16095 PROSPERITY DR,NOBLESVILLE,IN,46060,1128b7,20210816,00000000,00000000,NaN
3,115,NaN,NaN,,"AFFORDABLE PHARMACY, INC",OTHER BUSINESS,PHARMACY,NaN,1801231436,NaN,"8030 FM 1765, STE A104",TEXAS CITY,TX,77591,1128a1,20211029,00000000,00000000,NaN
4,121,NaN,NaN,,AIM PHARMACY AND SURGICALS COR,OTHER BUSINESS,PHARMACY,NaN,1912011800,NaN,1655 GRAND AVENUE,BALDWIN,NY,11510,1128b8,20220320,00000000,00000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,9673,BOHLMAN,ANDREW,LANCE,NaN,IND- LIC HC SERV PRO,CHIROPRACTIC,NaN,1306932678,19710109,P O BOX 17975,FOUNTAIN HILLS,AZ,85269,1128a1,20210120,00000000,00000000,NaN
286,9675,BOHLMAN,PETER,ANDREW JR,NaN,IND- LIC HC SERV PRO,PHYSICIAN ASSISTANT,NaN,1013064914,19670507,328 PINE STREET,SOUTH HEMPSTEAD,NY,11550,1128b4,20220119,00000000,00000000,NaN
287,9684,BOINPALLY,ASHOK,,NaN,"PHYSICIAN (MD, DO)",PEDIATRICS,NaN,1255421384,19520801,26868 HOLLY HILL DRIVE,FARMINGTON HILLS,MI,48334,1128a1,20200720,00000000,00000000,NaN
288,9720,BOLGER,PAUL,MATTHEW,NaN,"PHYSICIAN (MD, DO)",EMERGENCY MEDICINE,NaN,1376516609,19710923,"P O BOX 1000, #18202-030",MARION,IL,62959,1128a3,20190820,00000000,00000000,NaN
289,9938,BORDEN,WENDY,LYNN,NaN,EMPLOYEE - PRIVATE S,COUNSELING CENTER,NaN,1700216231,19730410,140 NORTH SEMINOLE LANE,LAKE ALFRED,FL,33850,1128a1,20220220,00000000,00000000,NaN

In [15]:
#Save the generated crime 2019 data
crime_data_2019.to_csv('crime_data/crime_Data_2019.csv',index = False)